### ISSUE TITLE
Use unreachable macro

### ISSUE THREAD

**Issue by L3P3** [Spickelbing/corrodoro#1]
https://github.com/Spickelbing/corrodoro/blob/fb3b5fdfd78a9f0488d6af954147ae5ecf1b6996/src/app.rs#LL212C1-L213C1

https://doc.rust-lang.org/std/macro.unreachable.html

**Comment by haitemura** [comment]
Kann man benutzen, bringt aber an der Stelle nicht mehr als ein Kommentar, weil dort lediglich `()` erwartet wird.
