### ISSUE TITLE
Audio-Format wählen und Codecs begrenzen

### ISSUE THREAD

**Issue by L3P3** [Spickelbing/corrodoro#2]
rodio unterstützt so einige Formate, für die normalerweise Codecs mitgeliefert werden.

Die wav-Datei ist unnötig groß, vielleicht wäre das Ergebnis kleiner mit flac, mp3 oder was auch immer.

Und dann, wenn du das passende Format gewählt hast, solltest du dafür sorgen, dass rodio nur mit diesem Codec kommt, indem du explizit das Feature festlegst in cargo.toml:

https://docs.rs/crate/rodio/latest/features

**Comment by haitemura** [comment]
Ungenutzte features entfernt in 62183ea

**Comment by L3P3** [comment]
Fein gemacht. Tipp: Am Anfang der Commit-Nachricht "#2" tun; dann wird der Issue hier referenziert.
